---
-
  get_url:
    dest: /home/{{user_name | quote }}
    group: "{{user_name | quote }}"
    mode: 493
    owner: "{{user_name | quote }}"
    url: "{{woocommerce_url}}"
  name: "Download woocommerce script using get_url"
-
  name: "Run a woocommerce script with arguments (using 'cmd' parameter)"
  shell: /home/{{user_name | quote }}/{{woocommerce_script_name}} {{ woocommerce_plugin_url | quote }}{{ woocommerce_version | quote }}.zip {{ user_name | quote }} {{ woocommerce_version | quote }} {{ webroot | quote }}
  args:
    executable: /bin/bash

-
  name: "Activate woocommerce with wp cli command"
  command: "wp plugin activate woocommerce --path='{{webroot}}/{{wordpress_dir}}'"